version: '3.9'

services:
  authlink:
    container_name: authlink
    build:
      context: .
      dockerfile: dockerfile.authlink
    restart: always
    ports:
      - 3020:3020
    depends_on:
      - postgres
    environment:
      - SESSION_STORAGE_PATH=/authlink-data
      - COOKIE_SECRET=ververysecretysecret*1234%^&*
      - PSQL_URI=postgres://postgres:postgres@postgres:5432/postgres
    volumes:
      - ./authlink-data:/authlink-data
      - ./authlink:/app
  postgres:
    image: postgres:13-alpine
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data/data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432